
import java.awt.event.ItemListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jhald
 */
public class Dialogo extends javax.swing.JDialog {

    private MenuPrincipal menuprincipal;
    /**
     * Creates new form Dialogo
     */
    public Dialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        menuprincipal = (MenuPrincipal)parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSpinnerfechadesde = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxtipococina = new javax.swing.JComboBox<>();
        jLabelTipo = new javax.swing.JLabel();
        jLabelnumero = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelcocina = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonsalir = new javax.swing.JButton();
        jTextFieldApellido = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldnombre = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelReservas = new javax.swing.JLabel();
        jLabelImgSalon = new javax.swing.JLabel();
        jLabelSalonHabana = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFechadesde = new javax.swing.JLabel();
        jTextFieldnumeroasistentes = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelNdias = new javax.swing.JLabel();
        jLabelNhabitaciones = new javax.swing.JLabel();
        jTextFieldNdias = new javax.swing.JTextField();
        jTextFieldNhabitaciones = new javax.swing.JTextField();
        jRadioButtonbanquete = new javax.swing.JRadioButton();
        jRadioButtoncongreso = new javax.swing.JRadioButton();
        jRadioButtonjornada = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        jSpinnerfechadesde.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jSpinnerfechadesde.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerfechadesde.setToolTipText("Selecciona la fecha ");

        jComboBoxtipococina.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jComboBoxtipococina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bufé", "Carta", "Menu Cerrado", "No Precisa" }));
        jComboBoxtipococina.setToolTipText("selecciona el tipo de cocina");

        jLabelTipo.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelTipo.setText("Tipo de evento:");
        jLabelTipo.setToolTipText("Seleccione tipo de evento");

        jLabelnumero.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelnumero.setText("Numero de asistentes:");
        jLabelnumero.setToolTipText("Cuantas personas asistirán");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelcocina.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelcocina.setText("Servicio de cocina:");
        jLabelcocina.setToolTipText("selecciona el tipo de cocina");

        jButtonAceptar.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("Validar la reserva");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonsalir.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jButtonsalir.setText("Salir");
        jButtonsalir.setToolTipText("Salir de la reserva");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });

        jTextFieldApellido.setToolTipText("Escribe tus apellidos");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextFieldnombre.setToolTipText("Escribe tu nombre");

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelReservas.setFont(new java.awt.Font("Vladimir Script", 2, 48)); // NOI18N
        jLabelReservas.setText("Reservas");

        jLabelImgSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salon01.jpeg"))); // NOI18N

        jLabelSalonHabana.setFont(new java.awt.Font("Vladimir Script", 2, 48)); // NOI18N
        jLabelSalonHabana.setText("Salón Habana");

        jLabelnombre.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelnombre.setText("Nombre:");
        jLabelnombre.setToolTipText("Escribe tu nombre");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel5.setText("Apellidos:");
        jLabel5.setToolTipText("Escribe tus apellidos ");

        jLabelFechadesde.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelFechadesde.setText("Fecha de entrada:");
        jLabelFechadesde.setToolTipText("Fecha del evento");

        jTextFieldnumeroasistentes.setToolTipText("Escribe el numero de asistentes");

        jLabelNdias.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelNdias.setText("Número de días:");
        jLabelNdias.setToolTipText("Días que dura el congreso");
        jLabelNdias.setEnabled(false);

        jLabelNhabitaciones.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabelNhabitaciones.setText("Número de Habitaciones:");
        jLabelNhabitaciones.setToolTipText("Cuantas habitaciones necesitas");
        jLabelNhabitaciones.setEnabled(false);

        jTextFieldNdias.setToolTipText("Escribe el numero de días");
        jTextFieldNdias.setDisabledTextColor(new java.awt.Color(51, 51, 0));
        jTextFieldNdias.setEnabled(false);
        jTextFieldNdias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNdiasActionPerformed(evt);
            }
        });

        jTextFieldNhabitaciones.setToolTipText("Escribe el numero de habitaciones");
        jTextFieldNhabitaciones.setDisabledTextColor(new java.awt.Color(51, 51, 0));
        jTextFieldNhabitaciones.setEnabled(false);

        buttonGroup1.add(jRadioButtonbanquete);
        jRadioButtonbanquete.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jRadioButtonbanquete.setText("Banquete");
        jRadioButtonbanquete.setToolTipText("Selecciona Banquete");
        jRadioButtonbanquete.setContentAreaFilled(false);
        jRadioButtonbanquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonbanqueteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtoncongreso);
        jRadioButtoncongreso.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jRadioButtoncongreso.setText("Congreso");
        jRadioButtoncongreso.setToolTipText("Seleciona Congreso");
        jRadioButtoncongreso.setContentAreaFilled(false);
        jRadioButtoncongreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtoncongresoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonjornada);
        jRadioButtonjornada.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jRadioButtonjornada.setText("Jornada");
        jRadioButtonjornada.setToolTipText("Selecciona Jornada");
        jRadioButtonjornada.setAutoscrolls(true);
        jRadioButtonjornada.setContentAreaFilled(false);
        jRadioButtonjornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonjornadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelImgSalon, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelSalonHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator1))
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelnombre)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTipo)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButtoncongreso)
                                .addGap(55, 55, 55)
                                .addComponent(jRadioButtonbanquete)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFechadesde)
                                    .addComponent(jSpinnerfechadesde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelnumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldnumeroasistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelcocina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxtipococina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNdias)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNdias, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabelNhabitaciones)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNhabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButtonjornada))))
                        .addContainerGap(94, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalonHabana, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelReservas))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelFechadesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerfechadesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldnumeroasistentes))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelcocina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxtipococina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonbanquete)
                            .addComponent(jRadioButtonjornada)
                            .addComponent(jRadioButtoncongreso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImgSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNdias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNhabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNdias, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNhabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
       
        setVisible(false);//Para volver al menu principal
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        System.exit(0);//boton para salir
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void jTextFieldNdiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNdiasActionPerformed
       
        
    }//GEN-LAST:event_jTextFieldNdiasActionPerformed

    private void jRadioButtoncongresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtoncongresoActionPerformed
       //cuando se selecciona el boton congreso se activan Nhabitacion y Ndias
        if (jRadioButtoncongreso.isSelected())
       {
       jLabelNhabitaciones.setEnabled(true);
       jLabelNdias.setEnabled(true);
       jTextFieldNdias.setEnabled(true);
       jTextFieldNhabitaciones.setEnabled(true);
       }
    
    }//GEN-LAST:event_jRadioButtoncongresoActionPerformed

    private void jRadioButtonbanqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonbanqueteActionPerformed
        //cuando se selecciona banquete se desactivan Nhabitaciones y Ndias
        if (jRadioButtonbanquete.isSelected()){
       jLabelNhabitaciones.setEnabled(false);
       jLabelNdias.setEnabled(false);
       jTextFieldNdias.setEnabled(false);
       jTextFieldNhabitaciones.setEnabled(false);
       }
    }//GEN-LAST:event_jRadioButtonbanqueteActionPerformed

    private void jRadioButtonjornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonjornadaActionPerformed
        //cuando se selecciona JOrnada se desactivan Nhabitaciones y Ndias
        if (jRadioButtonjornada.isSelected()){
       jLabelNhabitaciones.setEnabled(false);
       jLabelNdias.setEnabled(false);
       jTextFieldNdias.setEnabled(false);
       jTextFieldNhabitaciones.setEnabled(false);
       }
    }//GEN-LAST:event_jRadioButtonjornadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialogo dialog = new Dialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JComboBox<String> jComboBoxtipococina;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFechadesde;
    private javax.swing.JLabel jLabelImgSalon;
    private javax.swing.JLabel jLabelNdias;
    private javax.swing.JLabel jLabelNhabitaciones;
    private javax.swing.JLabel jLabelReservas;
    private javax.swing.JLabel jLabelSalonHabana;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelcocina;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabelnumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonbanquete;
    private javax.swing.JRadioButton jRadioButtoncongreso;
    private javax.swing.JRadioButton jRadioButtonjornada;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSpinner jSpinnerfechadesde;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNdias;
    private javax.swing.JTextField jTextFieldNhabitaciones;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldnumeroasistentes;
    // End of variables declaration//GEN-END:variables
}
