package Frame;


import java.io.File;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio
 */
public class Rejoj extends javax.swing.JFrame {
    //creación del metodo para ver la ayuda
    public void verAyuda() {
        //cargamos el fichero de ayuda hs
        File file = new File("help" + File.separator + "Ayuda.hs");//ruta
        //variables
        URL hsURL;
        HelpSet helpSet;
        try {
            hsURL = file.toURI().toURL();//conectamos
            helpSet = new HelpSet(getClass().getClassLoader(), hsURL);
            //Crea el helpset y el HelpBroker 
            HelpBroker hb = helpSet.createHelpBroker();
            //pone ayuda a item de menu 
            hb.enableHelpOnButton(jMenuItem1,"Introduccion1", helpSet);
            hb.enableHelpOnButton(jMenuItem2,"Uso1", helpSet);
            hb.enableHelpOnButton(botonAyuda,"Introduccion1", helpSet);
            
//Asociar a cada componente una página que se muestre al pulsar la tecla F1 sobre él.
            hb.enableHelp(jMenuItem1,"Introduccion1", helpSet);
            hb.enableHelp(jMenuItem2,"Uso1", helpSet);
//Hacer que el componente responda a la pulsación de la tecla de ayuda F1.            
            hb.enableHelpKey(getRootPane(),"Introduccion1", helpSet);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form NewJFrame
     */
    public Rejoj() {
        initComponents();
        verAyuda();
        //esta parte es para visualizar la hora de la alarma en JLabel3
        if (componenteRelojBean2.Hora_Alarma<10){
            if (componenteRelojBean2.Minutos_Alarma<10){
                jLabel3.setText("0"+String.valueOf(componenteRelojBean2.Hora_Alarma)+":0"+
                        String.valueOf(componenteRelojBean2.Minutos_Alarma));
            }else{
                 jLabel3.setText("0"+String.valueOf(componenteRelojBean2.Hora_Alarma)+":"+
                        String.valueOf(componenteRelojBean2.Minutos_Alarma));           
            }
        }
        else{
            if (componenteRelojBean2.Minutos_Alarma<10){
                jLabel3.setText(String.valueOf(componenteRelojBean2.Hora_Alarma)+":0"+
                    String.valueOf(componenteRelojBean2.Minutos_Alarma));
            }else{
                jLabel3.setText(String.valueOf(componenteRelojBean2.Hora_Alarma)+":"+
                    String.valueOf(componenteRelojBean2.Minutos_Alarma));
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componenteRelojBean2 = new componentes.ComponenteRelojBean();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonAyuda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        componenteRelojBean2.setActivar_Alarma(true);
        componenteRelojBean2.setHora_Alarma(19);
        componenteRelojBean2.setMensaje_Alarma("Buenos días Mundo");
        componenteRelojBean2.setMinutos_Alarma(17);
        componenteRelojBean2.setModo24(true);
        componenteRelojBean2.addDefinirAlarmaListener(new componentes.ComponenteRelojBean.DefinirAlarmaListener() {
            public void capturarAlarma(componentes.DefinirAlarmaEvent evt) {
                componenteRelojBean2CapturarAlarma(evt);
            }
        });
        getContentPane().add(componenteRelojBean2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 90, 20));

        jLabel1.setText("Hora Actual:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, 20));

        jLabel2.setText("Hora Alarma:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, 30));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 30));
        jLabel3.getAccessibleContext().setAccessibleName("Jlabel_Hora");

        botonAyuda.setText("AYUDA");
        botonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(botonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Creación del compoenente");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Uso del componente");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void componenteRelojBean2CapturarAlarma(componentes.DefinirAlarmaEvent evt) {//GEN-FIRST:event_componenteRelojBean2CapturarAlarma
        // TODO add your handling code here:
        //  JOptionPane.showMessageDialog(null, "La Alarma se ha activado", "Aviso",
        //JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null, componenteRelojBean2.Mensaje_Alarma, "Aviso",
        JOptionPane.INFORMATION_MESSAGE);

          componenteRelojBean2.activar_Alarma=false;
    }//GEN-LAST:event_componenteRelojBean2CapturarAlarma

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rejoj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rejoj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rejoj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rejoj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rejoj().setVisible(true);
            }           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAyuda;
    private componentes.ComponenteRelojBean componenteRelojBean2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
