package ejercicio2;
// Generated 14-dic-2021 17:54:33 by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int idmatricula;
     private Aulas aulas;
     private String nombre;
     private String apellidos;

    public Alumnos() {
    }

	
    public Alumnos(int idmatricula) {
        this.idmatricula = idmatricula;
    }
    public Alumnos(int idmatricula, Aulas aulas, String nombre, String apellidos) {
       this.idmatricula = idmatricula;
       this.aulas = aulas;
       this.nombre = nombre;
       this.apellidos = apellidos;
    }
   
    public int getIdmatricula() {
        return this.idmatricula;
    }
    
    public void setIdmatricula(int idmatricula) {
        this.idmatricula = idmatricula;
    }
    public Aulas getAulas() {
        return this.aulas;
    }
    
    public void setAulas(Aulas aulas) {
        this.aulas = aulas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }




}


