package ejercicio2;
// Generated 14-dic-2021 17:54:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aulas generated by hbm2java
 */
public class Aulas  implements java.io.Serializable {


     private int naula;
     private String nombre;
     private Integer capacidad;
     private Set alumnoses = new HashSet(0);

    public Aulas() {
    }

	
    public Aulas(int naula) {
        this.naula = naula;
    }
    public Aulas(int naula, String nombre, Integer capacidad, Set alumnoses) {
       this.naula = naula;
       this.nombre = nombre;
       this.capacidad = capacidad;
       this.alumnoses = alumnoses;
    }
   
    public int getNaula() {
        return this.naula;
    }
    
    public void setNaula(int naula) {
        this.naula = naula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }




}


