CREATE TABLE CLIENTES
(
IDCLIENTE NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(50),
DIRECCION VARCHAR2(50),
POBLACION VARCHAR2(50),
CODPOSTAL NUMBER(5),
PROVINCIA VARCHAR2(40),
NIF VARCHAR2(9) UNIQUE,
TELEFONO1 VARCHAR2(15),
TELEFONO2 VARCHAR2(15),
TELEFONO3 VARCHAR2(15)
);
 
CREATE TABLE PRODUCTOS
(
IDPRODUCTO NUMBER PRIMARY KEY,
DESCRIPCION VARCHAR2(80),
PVP NUMBER,
STOCKACTUAL NUMBER
);
 
CREATE TABLE VENTAS
(
IDVENTA NUMBER PRIMARY KEY,
IDCLIENTE NUMBER NOT NULL REFERENCES CLIENTES,
FECHAVENTA DATE
);
 
CREATE TABLE LINEASVENTAS
(
IDVENTA NUMBER,
NUMEROLINEA NUMBER,
IDPRODUCTO NUMBER,
CANTIDAD NUMBER,
FOREIGN KEY (IDVENTA) REFERENCES VENTAS (IDVENTA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS (IDPRODUCTO),
PRIMARY KEY (IDVENTA, NUMEROLINEA)
);
